# These are supported funding model platforms

github: [adityakarmalkar, openai, someuser123]
patreon: adityakarmalkar
open_collective: bashapath
ko_fi: akarmalkar
tidelift: npm/react
community_bridge: cloud-foundry
liberapay: adityakarmalkar
issuehunt: adityakarmalkar
lfx_crowdfunding: linux-foundation
polar: akdesigns
buy_me_a_coffee: akcoffee
thanks_dev: adityakarmalkar
